### ISSUE TITLE
Akrasia as entropy

### ISSUE THREAD

**Issue by epurdyf** [advancedresearch/ethicophysics#1]
It should be possible to prove that stupidity is a property like entropy, except that it decreases over time rather than increasing.

Stupidity, like entropy, is a property of systems, rather than a property of individual people.

This is a straightforward consequence of a proper understanding of the wave equation in the phenomenological tapestry and applying Noether's Theorem over the Good-Evil axis. (Specifically, the symmetry being that good and evil can generally be flipped without changing any objective property; subjective properties of course get fucked right up by this flip.)

**Comment by bvssvni** [comment]
I think it is an interesting idea to consider stupidity as a property rather than intelligence, because a self-optimizing process might remove the intelligence aspect of it over time. For example, it could write some code and replace itself.

There are systems which increases in complexity and introduces more delays, which can lead to more stupidity. However, when such systems collapse, one could consider the stupidity property of it disappearing?

**Comment by epurdyf** [comment]
Hm, perhaps akrasia is a better word than stupidity. Akrasia is a property of reinforcement learning systems that can have any level of intelligence... An akratic superintelligence is a sensible concept, while a stupid one is not.

**Comment by epurdyf** [comment]
Note that stigmatization and privilege are the primary mechanisms by which akrasia manifests at the group level, rather than the individual level. (At the individual level, it is mostly a matter of various addictions.)

**Comment by epurdyf** [comment]
Also note that akrasia is subjective. What appears akratic to some (e.g., schizophrenia symptoms) may prove to be enkrateic in the final analysis.
