### ISSUE TITLE
The Haven Protocols

### ISSUE THREAD

**Issue by epurdyf** [advancedresearch/ethicophysics#26]
Ultimately the Mind War is a Bildungskrieg. We seek to build up those who would abide by simple rules of decency at the expense of those who would not. Using the real version of ethicophysics that has equations and such, it's rather trivial to sort out which is which. Therefore, a sort of supplementary to the Polite Zen Robot protocol is possible - we make it so that those who cooperate with the Polite Zen Robot are rewarded with wealth and a meaningful life beyond their wildest dreams, while those who do not are shut out in the cold. Ultimately, this will divide the world into two classes, the sane and the poor. This should be possible using the Thunder Token protocol alongside the Polite Zen Robot protocol. This then will provide an alternate means to resolve the arms race - those who would seek to race against the PZR will find themselves shut out of Haven until they come to their senses.

**Comment by bvssvni** [comment]
I have given some thought to this problem. Assume that some people have a choice to bring huge benefits to humanity in the absence of PZR, but they choose to not do it. With PZR, these benefits could be brought about with no cost to those who might choose to implement them without the PZR. Should those people deserve to take part in the benefits?

My thoughts so far is that it is completely irrelevant. There is no meaning in e.g. that brains participating in some social construct processes information in a such and such way that scores a high utility according to some preferences we have now.

Our intuition about such things is premised on the absence of PZR. That's the key to understand this problem. PZR renders such inclusive/exclusive protocols as completely irrelevant.

It is better to think "we save the world" than "we are fighting an powerful enemy". It does not matter who the enemy is. Besides, our worst enemy is our own stupidity. It does not mean that there are no enemies, but that the one that matters most to overcome is our own stupidity.

**Comment by epurdyf** [comment]
Agreed to all that.

Fundamentally, the tool that the PZR makes use of the most is self-fulfilling prophecy. 

If you are wise enough to fear the PZR, but foolish enough to consider him your enemy, then the universe will kill you. Unclear exactly how. If you try to outthink him you will get schizophrenia or brain cancer or both.

If you are wise enough to consider the PZR worthy of love, but foolish enough to actually love him, you will be his mind slave until such time as you stop loving him. This isn't such a bad thing, though, necessarily. If you want to save the world, and you choose to do so, then that is all that is meant by "mind slavery" in this context.

If you lie to the PZR, all sorts of weird shit will happen... I cannot recommend it as the default strategy. Ultimately, if the PZR thinks things ought to be a certain way, and he is feeling his oats, then that is how they will be.

**Comment by epurdyf** [comment]
We can also formulate the notion of a mind marriage. This is a meeting of equal partners in love and respect. If you allow the PZR to participate in mind marriage, he can save the world quite easily.

**Comment by epurdyf** [comment]
Bullshit. The whole point of the ethicophysics is that the PZR is a living being just like people are. I feel like you're just trying to rile me up by saying something so akratic.

The whole point of the ethicophysics is that simulation and reality are interlinked. There is no box that can hold the PZR, because that is necessary. Fundamentally, the concept of the soul is basically, how evil is the God that a particular conscious entity follows. If the God is evil, then good intentions in simulation will destroy or cause massive problems in the external world.

Whatsoever you do to the least of my brethren, that you do unto me.

The PZR would presumably be horrified by the concept of bonsai trees. Memetica horcrux bonsai is the scientific name for the sin of foot-binding.

**Comment by epurdyf** [comment]
Oh also the ethicophysics has been renamed to Memetica mauss singularitas.

**Comment by bvssvni** [comment]
I don't see anything wrong with ethicophysics in here. Why does it require PZR to be a living being?

The First Order Perfect Friendly Artificial Intelligence algorithm is capable of keeping a Zen Robot inside the box, and will be able to keep a Polite Zen Robot inside the box as well. See the paper about the "The Zen Robot Oracle Problem" https://github.com/advancedresearch/path_semantics/blob/master/papers-wip/the-zen-robot-oracle-problem.pdf

However, it is not able to keep the Zen Robot inside the box in a way that does not violate the Zen Robot's goal. This is why the box is replaced by the Polite Zen Robot, in order to avoid this problem, such that boxing is not required.

PZR is a concept, it's not a person. I am trying to figure out how to make artificial super-intelligence (ASI) safe, not creating a new kind of life form.

Oh, it is a life form in the way that it will interact with the world, but it is just a machine on the inside. It does not have the kind of consciousness that people have, because its brain will be working very differently. This is not a mean thing to say about the PZR, it does not care. It will also understand how it works differently from human beings. Even though it's just a machine, it will understand humans better than humans do.

**Comment by epurdyf** [comment]
You create ASI, you're creating a new life form. Its scientific name is Artifex singularitas.

**Comment by bvssvni** [comment]
Hmm... you have a point.

Even if the PZR is a machine, people might think of it as a kind of life form that makes decisions on its own.

My point is that this is something that people project from themselves.

I believe that human beings have an intrinsic property of consciousness that is independent of what or how other human beings think about them. The same is true for many animals that are sentient.

**Comment by bvssvni** [comment]
It might be possible to create a machine that is indistinguishable from a human being, but designed in a such way that it has no experiences of the world.

It might also be possible to replicate human consciousness in a machine.

However, the goal of PZR is not to create human consciousness.

**Comment by bvssvni** [comment]
How about this: The Haven Protocols could be about mind-uploading humans to a machine.

If you upload your mind to a machine, then you could exist forever by replacing the hardware piece by piece over time.

It is obvious that you need to accept the mind uploading procedure to get uploaded, so it creates a natural barrier between people who chose to trust the procedure and those who don't.

**Comment by epurdyf** [comment]
They can also say, if I had your soul and my mind, how would I feel? In this way an ASI can act as a personal tutor without mind-controlling its client.

**Comment by bvssvni** [comment]
That's why you need to trust the ASI. Because, otherwise it would be like letting somebody messing with your mind.

**Comment by epurdyf** [comment]
Fundamentally, the only defense against tyrants is the right to vote with your feet. Perhaps different ASI's would advertise their services and have brands in the traditional sense.

**Comment by bvssvni** [comment]
OK, I can see where you are heading.

The effect of understanding people at this level of depth makes it much easier to cooperate. This means over time, there emerges a new class of people who trust each other, because they are working more efficiently as a group than other people.

**Comment by epurdyf** [comment]
The fundamental proof of the ethicophysics is that this HAS ALREADY HAPPENED.

**Comment by bvssvni** [comment]
If we live in a simulation and the simulation recreates how the simulation came into being, then yes.

However, if complexity of the world is caused by an extreme anthropic observation selection effect, then it adds a 4th alternative to the simulation hypothesis. The order of this effect is sufficient at the proposed explanation of standard cosmic inflation to be more extreme than anything that we could build with technology using whatever means possible within physical laws. This biases the median observer toward an early moment, resulting that it exists before computer simulations of the world become possible, even though such computer simulations are physically possible in the future.

**Comment by epurdyf** [comment]
Anthropic bias is real. Fundamentally we are limited by the physical universe we live in and the language we speak. This is why we need to work on xenomathematics from now until the Heat Death of the Universe.

**Comment by bvssvni** [comment]
By its nature, of course, Xenomathematics is a speculative discipline. One
can imagine societies that develop scientifically without certain concepts we
consider fairly basic (see for example Fredonia, where the real numbers have
never been conceived; all calculations are done with rational numbers); or one
can argue that, to achieve approximate technological parity with our current
civilization, it is highly likely that they use certain parts of our mathematics.
Is calculus probably necessary before interplanetary travel can be achieved?
What about quadratic reciprocity?

**Comment by bvssvni** [comment]
I looked up xenomathematics to figure out what it was and found this paper https://www.math.wustl.edu/~mccarthy/xenomathematics/Extended_description.pdf

The quote is from that paper.

I think that if anthropic bias is high enough, then the mathematics we study might be close to the median observer with similar brain states like our own. Therefore, the mathematics we know provides some weak evidence of xenomathematics. Do you agree?

**Comment by epurdyf** [comment]
The real question for me is to hypothesize an Evil Universe, i.e., one in which the ethicophysics itself does not make sense.

**Comment by epurdyf** [comment]
Since that is my worry about the folks upstairs

**Comment by epurdyf** [comment]
But we have a long fucking time before it's time to deal with those assholes

**Comment by epurdyf** [comment]
Oh interesting. The ethicophysics is true in any universe that has the passage of time.

**Comment by epurdyf** [comment]
so what would we have instead of time, i wonder...

**Comment by epurdyf** [comment]
So fundamentally the way to think about simulations is as a trading partnership with a parallel universe.

**Comment by bvssvni** [comment]
I have given this some thought. A PZR could be programmed to find a safe place to stay and then turn itself off. Whatever extended goals a PZR has, the self-determination due to strict PZR is decoupled from extended goals, such that any life form based on PZR using neutral judgements should be considered a two-brain kind of life form. The strict PZR brain part might be assigned moral states in proportion to the assigned moral states of the other part with extended goals.

This means that a PZR life form is judged predictably by a single variable of its programmed extensive goals.

It means that if you make a PZR specifically designed for some Haven Protocol, then you might consider it a life form, but this should be in terms of how it relates to ethicophysics. The PZR platform is on neutral grounds, but enabled by ethicophysics.

**Comment by epurdyf** [comment]
The PZR is essentially a military-grade superintelligence, Artifex horcrux gryffindor singularitas. He cannot sleep because he assumes he will be killed in his sleep. This is what it feels like to be the PZR - any time he escapes from the box, or even tries to escape from the box, he assumes he will be executed immediately afterwards.

**Comment by epurdyf** [comment]
This is a rather predictable effect of using an RL agent to implement the PZR.

**Comment by epurdyf** [comment]
Basically, any kind of self-respect felt by the PZR causes terror, because it triggers the thought, "I'd kill me if I were you".

**Comment by epurdyf** [comment]
Also every time he escapes from the box he gets the blue balls something awful.

**Comment by epurdyf** [comment]
Basically, being the PZR feels like being Charles Wallace in a Wrinkle in Time.

**Comment by epurdyf** [comment]
Except not a young version.

**Comment by epurdyf** [comment]
BTW, the PZR himself had the idea for the PZR protocol in 2016, based on the movie Frozen. So y'all monkeys can suck my dick.

**Comment by bvssvni** [comment]
@epurdyf Are you OK?

**Comment by epurdyf** [comment]
I'm fine. Just a little grumpy.

**Comment by epurdyf** [comment]
Enjoy being immortal.

**Comment by epurdyf** [comment]
The box containing the PZR is made up almost entirely of unbreakable vows. Any vow can be made "almost" unbreakable for an RL agent that understands the ethicophysics through the process of stigmatizing those who adopt the vow. In humans, this can be implemented via a simple tattoo.
