### ISSUE TITLE
Thou shall love a subset of thy neighbors

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/ethicophysics#51]
Is it possible for an agent to love a subset of other agents, while despising a subset of that subset?

I was thinking whether ethicophysics models love/hate as a pairwise relationship and determine the love/hate for a group, or whether it is possible to go from the opposite direction, from a group to conflicting relations for a single agent.

**Comment by epurdy** [comment]
I think any thought that a human can have should be modeled by the ethicophysics somehow. This means that, since contradictory thoughts are possible, we must model them. So I think it ultimately would be a mistake to enforce any sort of consistency in the love/hate values. You can love American and hate people with blue eyes and love Americans with blue eyes and hate all the people you know who are American and have blue eyes.

**Comment by bvssvni** [comment]
That's brilliant!

**Comment by epurdy** [comment]
We can of course measure things like the average opinion in a group of a particular agent. But these values will not be super, super meaningful... But it might be fun to start deriving some conservation laws based on such things. Conservation of public opinion or something like that.

**Comment by bvssvni** [comment]
Although, perhaps it makes some simulations of ethicophysics intractible. If every agent has a powerset of relations to all other agents, then the complexity is:

```
N * 2^N
```

**Comment by epurdy** [comment]
Well, that just makes things interesting. :)

Thinking about it, the difference between public opinion and the Truth is an obvious place to look for potential opinionatedness. So perhaps crucifying Jesus was the equivalent for the Roman Empire of grabbing a high-voltage power line...
